-- ============================================
-- Generated product data
-- Generated on 2026-05-21T20:40:22
-- ============================================
BEGIN;

-- ===== case-accessory (Case Accessory) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'NZXT HUE 2 RGB Lighting Kit', 'LED Controller', 0.00, 0, 5, (SELECT id FROM categories WHERE name = 'Case Accessory'), '{"name":"NZXT HUE 2 RGB Lighting Kit","type":"LED Controller","form_factor":2.5,"brand":"NZXT","source_file":"case-accessory.jsonl","source_category":"Case Accessory"}'::jsonb, '{"manufacturer":"NZXT","type":"LED Controller","form_factor":"2.5","compatibility":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'NZXT HUE 2 RGB Lighting Kit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'NZXT Hue+', 'LED Controller', 0.00, 0, 5, (SELECT id FROM categories WHERE name = 'Case Accessory'), '{"name":"NZXT Hue+","type":"LED Controller","form_factor":2.5,"brand":"NZXT","source_file":"case-accessory.jsonl","source_category":"Case Accessory"}'::jsonb, '{"manufacturer":"NZXT","type":"LED Controller","form_factor":"2.5","compatibility":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'NZXT Hue+' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory'));

-- ===== case-fan (Case Fan) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Lian Li Uni Fan SL-Infinity 3-Pack', '120mm Fan', 2250000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Case Fan'), '{"name":"Lian Li Uni Fan SL-Infinity 3-Pack","size":120,"color":"Black","rpm":null,"airflow":[0,61.3],"noise_level":[0,29],"pwm":true,"brand":"Lian","source_file":"case-fan.jsonl","source_category":"Case Fan"}'::jsonb, '{"manufacturer":null,"size":120,"rpm":null,"airflow":"0-61.3 CFM","noise_level":"0-29 dBA","pwm":true,"bearing_type":null,"rgb":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Lian Li Uni Fan SL-Infinity 3-Pack' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Noctua NF-A12x25 PWM chromax.black.swap', '120mm Fan', 949000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Case Fan'), '{"name":"Noctua NF-A12x25 PWM chromax.black.swap","size":120,"color":"Black","rpm":[450,2000],"airflow":60.09,"noise_level":22.6,"pwm":true,"brand":"Noctua","source_file":"case-fan.jsonl","source_category":"Case Fan"}'::jsonb, '{"manufacturer":"Noctua","size":120,"rpm":"450-2000 RPM","airflow":"60.09 CFM","noise_level":"22.6 dBA","pwm":true,"bearing_type":null,"rgb":"No"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Noctua NF-A12x25 PWM chromax.black.swap' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan'));

-- ===== case (Case) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Montech XR', 'ATX Mid Tower', 2090000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Case'), '{"name":"Montech XR","type":"ATX Mid Tower","color":"Black","psu":null,"side_panel":"Tempered Glass","external_volume":45,"internal_35_bays":2,"brand":"Montech","source_file":"case.jsonl","source_category":"Case"}'::jsonb, '{"manufacturer":null,"type":"ATX Mid Tower","motherboard_support":"ATX","color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Montech XR' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Phanteks XT PRO', 'ATX Mid Tower', 1700000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Case'), '{"name":"Phanteks XT PRO","type":"ATX Mid Tower","color":"Black","psu":null,"side_panel":"Tempered Glass","external_volume":51.8,"internal_35_bays":2,"brand":"Phanteks","source_file":"case.jsonl","source_category":"Case"}'::jsonb, '{"manufacturer":"Phanteks","type":"ATX Mid Tower","motherboard_support":"ATX","color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Phanteks XT PRO' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case'));

-- ===== cpu-cooler (CPU Cooler) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Thermalright Peerless Assassin 120 SE', 'Thermalright Peerless Assassin 120 SE', 872000.00, 20, 5, (SELECT id FROM categories WHERE name = 'CPU Cooler'), '{"name":"Thermalright Peerless Assassin 120 SE","rpm":1550,"noise_level":25.6,"color":"Black / Silver","size":null,"brand":"Thermalright","source_file":"cpu-cooler.jsonl","source_category":"CPU Cooler"}'::jsonb, '{"manufacturer":"Thermalright","type":null,"socket_compatibility":null,"radiator_size":120,"fan_size":120,"height":120,"tdp_rating":null,"noise_level":"25.6 dBA"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Thermalright Peerless Assassin 120 SE' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'ARCTIC Liquid Freezer III Pro 360', 'ARCTIC Liquid Freezer III Pro 360', 2125000.00, 20, 5, (SELECT id FROM categories WHERE name = 'CPU Cooler'), '{"name":"ARCTIC Liquid Freezer III Pro 360","rpm":[600,3000],"noise_level":null,"color":"Black","size":360,"brand":"ARCTIC","source_file":"cpu-cooler.jsonl","source_category":"CPU Cooler"}'::jsonb, '{"manufacturer":"Arctic","type":"Liquid","socket_compatibility":null,"radiator_size":360,"fan_size":null,"height":null,"tdp_rating":null,"noise_level":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'ARCTIC Liquid Freezer III Pro 360' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler'));

-- ===== cpu (CPU) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'AMD Ryzen 7 9800X3D', '8C/4.7GHz Zen 5', 11288000.00, 20, 5, (SELECT id FROM categories WHERE name = 'CPU'), '{"name":"AMD Ryzen 7 9800X3D","core_count":8,"core_clock":4.7,"boost_clock":5.2,"microarchitecture":"Zen 5","tdp":120,"graphics":"Radeon","brand":"AMD","source_file":"cpu.jsonl","source_category":"CPU"}'::jsonb, '{"manufacturer":"AMD","series":"AMD Ryzen 7","generation":"AMD Zen 5","socket":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'AMD Ryzen 7 9800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'AMD Ryzen 7 7800X3D', '8C/4.2GHz Zen 4', 8501000.00, 20, 5, (SELECT id FROM categories WHERE name = 'CPU'), '{"name":"AMD Ryzen 7 7800X3D","core_count":8,"core_clock":4.2,"boost_clock":5,"microarchitecture":"Zen 4","tdp":120,"graphics":"Radeon","brand":"AMD","source_file":"cpu.jsonl","source_category":"CPU"}'::jsonb, '{"manufacturer":"AMD","series":"AMD Ryzen 7","generation":null,"socket":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'AMD Ryzen 7 7800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU'));

-- ===== external-hard-drive (External Hard Drive) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Apricorn Aegis Fortress L3', 'Portable', 324975000.00, 20, 5, (SELECT id FROM categories WHERE name = 'External Hard Drive'), '{"name":"Apricorn Aegis Fortress L3","type":"Portable","interface":"USB Type-A 3.2 Gen 1, USB Type-C 3.2 Gen 1","capacity":20000,"price_per_gb":0.65,"color":"Black","brand":"Apricorn","source_file":"external-hard-drive.jsonl","source_category":"External Hard Drive"}'::jsonb, '{"manufacturer":null,"capacity":20000,"type":"Portable","interface":"USB Type-A 3.2 Gen 1, USB Type-C 3.2 Gen 1","portable":true,"price_per_gb":0.65,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Apricorn Aegis Fortress L3' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Western Digital My Book Duo', 'Desktop', 30000000.00, 20, 5, (SELECT id FROM categories WHERE name = 'External Hard Drive'), '{"name":"Western Digital My Book Duo","type":"Desktop","interface":"USB Type-A 3.2 Gen 1, USB Type-C 3.2 Gen 1","capacity":44000,"price_per_gb":0.027,"color":"Black","brand":"Western Digital","source_file":"external-hard-drive.jsonl","source_category":"External Hard Drive"}'::jsonb, '{"manufacturer":null,"capacity":44000,"type":"Desktop","interface":"USB Type-A 3.2 Gen 1, USB Type-C 3.2 Gen 1","portable":false,"price_per_gb":0.027,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Western Digital My Book Duo' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive'));

-- ===== fan-controller (Fan Controller) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'ARCTIC Case Fan Hub', 'ARCTIC Case Fan Hub', 250000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Fan Controller'), '{"name":"ARCTIC Case Fan Hub","channels":10,"channel_wattage":null,"pwm":true,"form_factor":null,"color":"Black","brand":"ARCTIC","source_file":"fan-controller.jsonl","source_category":"Fan Controller"}'::jsonb, '{"manufacturer":null,"channels":10,"channel_wattage":10,"pwm_support":null,"form_factor":null,"display":null,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'ARCTIC Case Fan Hub' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Lian Li UNI HUB – SL Controller', 'Lian Li UNI HUB – SL Controller', 0.00, 0, 5, (SELECT id FROM categories WHERE name = 'Fan Controller'), '{"name":"Lian Li UNI HUB – SL Controller","channels":4,"channel_wattage":null,"pwm":true,"form_factor":null,"color":"Black","brand":"Lian","source_file":"fan-controller.jsonl","source_category":"Fan Controller"}'::jsonb, '{"manufacturer":null,"channels":4,"channel_wattage":null,"pwm_support":null,"form_factor":null,"display":null,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Lian Li UNI HUB – SL Controller' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller'));

-- ===== headphones (Headphones) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'HP HyperX Cloud II', 'Circumaural', 1774000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Headphones'), '{"name":"HP HyperX Cloud II","type":"Circumaural","frequency_response":[15,25],"microphone":true,"wireless":false,"enclosure_type":"Closed","color":"Black / Red","brand":"HP","source_file":"headphones.jsonl","source_category":"Headphones"}'::jsonb, '{"manufacturer":null,"type":"Circumaural","connection":null,"microphone":true,"noise_cancelling":null,"frequency_response":"15-25 Hz","enclosure_type":"Closed","color":"Black / Red"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'HP HyperX Cloud II' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'HiFiMAN Susvara', 'Circumaural', 149975000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Headphones'), '{"name":"HiFiMAN Susvara","type":"Circumaural","frequency_response":[6,75],"microphone":false,"wireless":false,"enclosure_type":"Open","color":"Silver / Brown","brand":"HiFiMAN","source_file":"headphones.jsonl","source_category":"Headphones"}'::jsonb, '{"manufacturer":null,"type":"Circumaural","connection":null,"microphone":false,"noise_cancelling":null,"frequency_response":"6-75 Hz","enclosure_type":"Open","color":"Silver / Brown"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'HiFiMAN Susvara' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones'));

-- ===== internal-hard-drive (Internal Hard Drive) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Samsung 990 Pro', 'SSD', 3750000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Internal Hard Drive'), '{"name":"Samsung 990 Pro","capacity":2000,"price_per_gb":0.075,"type":"SSD","cache":2048,"form_factor":"M.2-2280","interface":"M.2 PCIe 4.0 X4","brand":"Samsung","source_file":"internal-hard-drive.jsonl","source_category":"Internal Hard Drive"}'::jsonb, '{"manufacturer":"Samsung","capacity":2000,"type":"SSD","form_factor":"M.2-2280","interface":"M.2 PCIe 4.0 X4","cache":2048,"price_per_gb":0.075}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Samsung 990 Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Crucial P3 Plus', 'SSD', 1424000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Internal Hard Drive'), '{"name":"Crucial P3 Plus","capacity":1000,"price_per_gb":0.057,"type":"SSD","cache":null,"form_factor":"M.2-2280","interface":"M.2 PCIe 4.0 X4","brand":"Crucial","source_file":"internal-hard-drive.jsonl","source_category":"Internal Hard Drive"}'::jsonb, '{"manufacturer":null,"capacity":1000,"type":"SSD","form_factor":"M.2-2280","interface":"M.2 PCIe 4.0 X4","cache":null,"price_per_gb":0.057}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Crucial P3 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive'));

-- ===== keyboard (Keyboard) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'HP HyperX Alloy Core', 'Gaming', 950000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Keyboard'), '{"name":"HP HyperX Alloy Core","style":"Gaming","switches":null,"backlit":"RGB","tenkeyless":false,"connection_type":"Wired","color":"Black","brand":"HP","source_file":"keyboard.jsonl","source_category":"Keyboard"}'::jsonb, '{"manufacturer":null,"layout":null,"switch_type":"Cherry MX Red","connection":"Wired","backlit":"RGB","hot_swap":null,"media_keys":null,"color":"Black","tenkeyless":false}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'HP HyperX Alloy Core' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Redragon K552', 'Gaming', 875000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Keyboard'), '{"name":"Redragon K552","style":"Gaming","switches":"Outemu Blue","backlit":"Red","tenkeyless":true,"connection_type":"Wired","color":"Black","brand":"Redragon","source_file":"keyboard.jsonl","source_category":"Keyboard"}'::jsonb, '{"manufacturer":null,"layout":null,"switch_type":"Cherry MX Red","connection":"Wired","backlit":"Red","hot_swap":null,"media_keys":null,"color":"Black","tenkeyless":true}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Redragon K552' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard'));

-- ===== memory (Memory) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Corsair Vengeance RGB 32 GB', '2 x 16GB DDR5-6000', 2375000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Memory'), '{"name":"Corsair Vengeance RGB 32 GB","speed":[5,6000],"modules":[2,16],"price_per_gb":2.968,"color":"Black","first_word_latency":12,"cas_latency":36,"brand":"Corsair","source_file":"memory.jsonl","source_category":"Memory"}'::jsonb, '{"manufacturer":"Corsair","type":null,"capacity":4,"bus_speed":null,"ecc":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Corsair Vengeance RGB 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'G.Skill Flare X5 32 GB', '2 x 16GB DDR5-6000', 2250000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Memory'), '{"name":"G.Skill Flare X5 32 GB","speed":[5,6000],"modules":[2,16],"price_per_gb":2.812,"color":"Black","first_word_latency":12,"cas_latency":36,"brand":"G.Skill","source_file":"memory.jsonl","source_category":"Memory"}'::jsonb, '{"manufacturer":"G.Skill","type":null,"capacity":8,"bus_speed":null,"ecc":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'G.Skill Flare X5 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory'));

-- ===== monitor (Monitor) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'KOORUI 24E3', '24" 1920x1080', 2750000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Monitor'), '{"name":"KOORUI 24E3","screen_size":24,"resolution":[1920,1080],"refresh_rate":165,"response_time":1,"panel_type":"IPS","aspect_ratio":"16:9","brand":"KOORUI","source_file":"monitor.jsonl","source_category":"Monitor"}'::jsonb, '{"manufacturer":null,"size":24,"resolution":"1920x1080","refresh_rate":165,"response_time":1,"brightness":null,"connectivity":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'KOORUI 24E3' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Asus TUF Gaming VG27AQ', '27" 2560x1440', 6225000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Monitor'), '{"name":"Asus TUF Gaming VG27AQ","screen_size":27,"resolution":[2560,1440],"refresh_rate":165,"response_time":1,"panel_type":"IPS","aspect_ratio":"16:9","brand":"ASUS","source_file":"monitor.jsonl","source_category":"Monitor"}'::jsonb, '{"manufacturer":"ASUS","size":24,"resolution":"2560x1440","refresh_rate":165,"response_time":1,"brightness":null,"connectivity":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Asus TUF Gaming VG27AQ' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor'));

-- ===== motherboard (Motherboard) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Asus PRIME B650-PLUS WIFI', 'AM5', 4000000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Motherboard'), '{"name":"Asus PRIME B650-PLUS WIFI","socket":"AM5","form_factor":"ATX","max_memory":192,"memory_slots":4,"color":"Black / Silver","brand":"ASUS","source_file":"motherboard.jsonl","source_category":"Motherboard"}'::jsonb, '{"manufacturer":"ASUS","socket":"AM5","form_factor":"ATX","chipset":"B650","ram_slots":2}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Asus PRIME B650-PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'MSI B650 GAMING PLUS WIFI', 'AM5', 4250000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Motherboard'), '{"name":"MSI B650 GAMING PLUS WIFI","socket":"AM5","form_factor":"ATX","max_memory":192,"memory_slots":4,"color":"Black","brand":"MSI","source_file":"motherboard.jsonl","source_category":"Motherboard"}'::jsonb, '{"manufacturer":"MSI","socket":"AM5","form_factor":"ATX","chipset":"B650","ram_slots":2}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'MSI B650 GAMING PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard'));

-- ===== mouse (Mouse) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Logitech G305 LIGHTSPEED', 'Optical', 750000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Mouse'), '{"name":"Logitech G305 LIGHTSPEED","tracking_method":"Optical","connection_type":"Wired, Wireless","max_dpi":12000,"hand_orientation":"Right","color":"Black","brand":"Logitech","source_file":"mouse.jsonl","source_category":"Mouse"}'::jsonb, '{"manufacturer":"Logitech","sensor_type":"Optical","max_dpi":12000,"buttons":2,"connection":"Wired","hand_orientation":"Right","free_scroll":null,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Logitech G305 LIGHTSPEED' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Logitech G502 Hero', 'Optical', 1119000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Mouse'), '{"name":"Logitech G502 Hero","tracking_method":"Optical","connection_type":"Wired","max_dpi":25600,"hand_orientation":"Right","color":"Black","brand":"Logitech","source_file":"mouse.jsonl","source_category":"Mouse"}'::jsonb, '{"manufacturer":"Logitech","sensor_type":"Optical","max_dpi":25600,"buttons":2,"connection":"Wired","hand_orientation":"Right","free_scroll":null,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Logitech G502 Hero' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse'));

-- ===== optical-drive (Optical Drive) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'LG WH14NS40', 'LG WH14NS40', 2500000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Optical Drive'), '{"name":"LG WH14NS40","bd":12,"dvd":16,"cd":48,"bd_write":"14/12/2/2","dvd_write":"16/8/8/16/6/8/5","cd_write":"48/24","brand":"LG","source_file":"optical-drive.jsonl","source_category":"Optical Drive"}'::jsonb, '{"manufacturer":"LG","type":null,"read_speeds":null,"write_speeds":null,"interface":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'LG WH14NS40' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Lite-On iHAS124-14', 'Lite-On iHAS124-14', 722000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Optical Drive'), '{"name":"Lite-On iHAS124-14","bd":null,"dvd":16,"cd":48,"bd_write":null,"dvd_write":"24/8/8/24/6/8/5","cd_write":"48/24","brand":"Lite-On","source_file":"optical-drive.jsonl","source_category":"Optical Drive"}'::jsonb, '{"manufacturer":null,"type":null,"read_speeds":null,"write_speeds":null,"interface":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Lite-On iHAS124-14' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive'));

-- ===== os (Operating System) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Microsoft Windows 11 Home OEM - DVD 64-bit', 'Microsoft Windows 11 Home OEM - DVD 64-bit', 2750000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Operating System'), '{"name":"Microsoft Windows 11 Home OEM - DVD 64-bit","mode":64,"max_memory":128,"brand":"Microsoft","source_file":"os.jsonl","source_category":"Operating System"}'::jsonb, '{"manufacturer":"Microsoft Windows","version":"Windows 11 Home","architecture":"32-bit","license_type":"Home","product_type":"CD/DVD","max_memory":128}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Microsoft Windows 11 Home OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Microsoft Windows 11 Pro OEM - DVD 64-bit', 'Microsoft Windows 11 Pro OEM - DVD 64-bit', 3654000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Operating System'), '{"name":"Microsoft Windows 11 Pro OEM - DVD 64-bit","mode":64,"max_memory":2048,"brand":"Microsoft","source_file":"os.jsonl","source_category":"Operating System"}'::jsonb, '{"manufacturer":"Microsoft Windows","version":"Windows 11 Pro","architecture":"32-bit","license_type":"Pro","product_type":"CD/DVD","max_memory":2048}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Microsoft Windows 11 Pro OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System'));

-- ===== power-supply (Power Supply) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'MSI MAG A750GL PCIE5', '750W gold', 2750000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Power Supply'), '{"name":"MSI MAG A750GL PCIE5","type":"ATX","efficiency":"gold","wattage":750,"modular":"Full","color":"Black","brand":"MSI","source_file":"power-supply.jsonl","source_category":"Power Supply"}'::jsonb, '{"manufacturer":"MSI","wattage":750,"efficiency":"Gold","modular":"Full","form_factor":"FLEX ATX"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'MSI MAG A750GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'MSI MAG A850GL PCIE5', '850W gold', 3050000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Power Supply'), '{"name":"MSI MAG A850GL PCIE5","type":"ATX","efficiency":"gold","wattage":850,"modular":"Full","color":"Black","brand":"MSI","source_file":"power-supply.jsonl","source_category":"Power Supply"}'::jsonb, '{"manufacturer":"MSI","wattage":850,"efficiency":"Gold","modular":"Full","form_factor":"FLEX ATX"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'MSI MAG A850GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply'));

-- ===== sound-card (Sound Card) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Creative Labs Sound BlasterX AE-5 Plus', 'Sound Core3D', 4037000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Sound Card'), '{"name":"Creative Labs Sound BlasterX AE-5 Plus","channels":5.1,"digital_audio":32,"snr":122,"sample_rate":384,"chipset":"Sound Core3D","interface":"PCIe x1","brand":"Creative","source_file":"sound-card.jsonl","source_category":"Sound Card"}'::jsonb, '{"manufacturer":"Creative","channels":"5.1","interface":"PCIe x1","sample_rate":384,"bit_depth":16,"snr":122,"chipset":"Sound Core3D","ports":3}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Creative Labs Sound BlasterX AE-5 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Creative Labs Sound Blaster AE-9', 'Sound Core3D', 10687000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Sound Card'), '{"name":"Creative Labs Sound Blaster AE-9","channels":7.1,"digital_audio":32,"snr":129,"sample_rate":384,"chipset":"Sound Core3D","interface":"PCIe x1","brand":"Creative","source_file":"sound-card.jsonl","source_category":"Sound Card"}'::jsonb, '{"manufacturer":"Creative","channels":"7.1","interface":"PCIe x1","sample_rate":384,"bit_depth":32,"snr":129,"chipset":"Sound Core3D","ports":3}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Creative Labs Sound Blaster AE-9' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card'));

-- ===== speakers (Speakers) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Creative Labs Pebble 2.0', '2', 725000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Speakers'), '{"name":"Creative Labs Pebble 2.0","configuration":2,"wattage":4.4,"frequency_response":[100,17],"color":"Black","brand":"Creative","source_file":"speakers.jsonl","source_category":"Speakers"}'::jsonb, '{"manufacturer":null,"configuration":"2.0","power":null,"connection":null,"frequency_response":"100-17 Hz","color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Creative Labs Pebble 2.0' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'SteelSeries Arena 9 EU', '5.1', 21926000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Speakers'), '{"name":"SteelSeries Arena 9 EU","configuration":5.1,"wattage":null,"frequency_response":[35,20],"color":"Black","brand":"SteelSeries","source_file":"speakers.jsonl","source_category":"Speakers"}'::jsonb, '{"manufacturer":null,"configuration":"5.1","power":null,"connection":null,"frequency_response":"35-20 Hz","color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'SteelSeries Arena 9 EU' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers'));

-- ===== thermal-paste (Thermal Paste) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Arctic Silver 5 High-Density Polysynthetic Silver', 'Arctic Silver 5 High-Density Polysynthetic Silver', 199000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Thermal Paste'), '{"name":"Arctic Silver 5 High-Density Polysynthetic Silver","amount":3.5,"brand":"Arctic","source_file":"thermal-paste.jsonl","source_category":"Thermal Paste"}'::jsonb, '{"manufacturer":"Arctic","amount":3.5,"conductivity":null,"type":null,"application_method":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Arctic Silver 5 High-Density Polysynthetic Silver' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Thermal Grizzly Kryonaut', 'Thermal Grizzly Kryonaut', 194000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Thermal Paste'), '{"name":"Thermal Grizzly Kryonaut","amount":1,"brand":"Thermal","source_file":"thermal-paste.jsonl","source_category":"Thermal Paste"}'::jsonb, '{"manufacturer":"Thermal Grizzly","amount":1,"conductivity":null,"type":null,"application_method":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Thermal Grizzly Kryonaut' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste'));

-- ===== ups (UPS) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'CyberPower CP1500PFCLCD', '1500', 5999000.00, 20, 5, (SELECT id FROM categories WHERE name = 'UPS'), '{"name":"CyberPower CP1500PFCLCD","capacity_w":1000,"capacity_va":1500,"brand":"CyberPower","source_file":"ups.jsonl","source_category":"UPS"}'::jsonb, '{"manufacturer":"CyberPower","capacity_va":1500,"capacity_w":1000,"battery_runtime":null,"outlets":10,"type":null,"surge_protection":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'CyberPower CP1500PFCLCD' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'APC SURT20KRMXLT', '20000', 602500000.00, 20, 5, (SELECT id FROM categories WHERE name = 'UPS'), '{"name":"APC SURT20KRMXLT","capacity_w":16000,"capacity_va":20000,"brand":"APC","source_file":"ups.jsonl","source_category":"UPS"}'::jsonb, '{"manufacturer":"APC","capacity_va":20000,"capacity_w":16000,"battery_runtime":null,"outlets":4,"type":null,"surge_protection":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'APC SURT20KRMXLT' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS'));

-- ===== video-card (Video Card) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'MSI GeForce RTX 3060 Ventus 2X 12G', 'GeForce RTX 3060 12GB', 7499000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Video Card'), '{"name":"MSI GeForce RTX 3060 Ventus 2X 12G","chipset":"GeForce RTX 3060 12GB","memory":12,"core_clock":1320,"boost_clock":1777,"color":"Black","length":235,"brand":"MSI","source_file":"video-card.jsonl","source_category":"Video Card"}'::jsonb, '{"manufacturer":"MSI","memory_type":null,"memory_size":2,"memory_bus":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'MSI GeForce RTX 3060 Ventus 2X 12G' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Sapphire PULSE', 'Radeon RX 9060 XT', 9500000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Video Card'), '{"name":"Sapphire PULSE","chipset":"Radeon RX 9060 XT","memory":16,"core_clock":2220,"boost_clock":3290,"color":"Black","length":240,"brand":"Sapphire","source_file":"video-card.jsonl","source_category":"Video Card"}'::jsonb, '{"manufacturer":"Sapphire","memory_type":null,"memory_size":2,"memory_bus":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Sapphire PULSE' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card'));

-- ===== webcam (Webcam) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Razer Kiyo Pro Ultra', '4k', 7500000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Webcam'), '{"name":"Razer Kiyo Pro Ultra","resolutions":["4k","2k","1080p","720p"],"connection":"USB 3.2 Gen 1 Type-A","focus_type":"Auto","os":["Windows"],"fov":82,"brand":"Razer","source_file":"webcam.jsonl","source_category":"Webcam"}'::jsonb, '{"manufacturer":"Razer","resolution":"720p","frame_rate":null,"connection":"USB 3.2 Gen 1 Type-A","fov":82,"focus_type":"Auto","os_support":"Windows"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Razer Kiyo Pro Ultra' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Logitech BRIO Ultra HD Pro', '4k', 3325000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Webcam'), '{"name":"Logitech BRIO Ultra HD Pro","resolutions":["4k","1080p","720p"],"connection":"USB 3.2 Gen 1 Type-A","focus_type":"Auto","os":["Windows","OS X","ChromeOS"],"fov":82,"brand":"Logitech","source_file":"webcam.jsonl","source_category":"Webcam"}'::jsonb, '{"manufacturer":"Logitech","resolution":"720p","frame_rate":null,"connection":"USB 3.2 Gen 1 Type-A","fov":82,"focus_type":"Auto","os_support":"Windows"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Logitech BRIO Ultra HD Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam'));

-- ===== wired-network-card (Wired Network Card) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'TP-Link TG-3468', 'PCIe x1', 375000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Wired Network Card'), '{"name":"TP-Link TG-3468","interface":"PCIe x1","color":null,"brand":"TP-Link","source_file":"wired-network-card.jsonl","source_category":"Wired Network Card"}'::jsonb, '{"manufacturer":"TP-Link","speed":null,"interface":"PCIe x1","chipset":null,"color":null}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'TP-Link TG-3468' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'StarTech ST10GPEXNDPI', 'PCIe x4', 11324000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Wired Network Card'), '{"name":"StarTech ST10GPEXNDPI","interface":"PCIe x4","color":"Black / Silver","brand":"StarTech","source_file":"wired-network-card.jsonl","source_category":"Wired Network Card"}'::jsonb, '{"manufacturer":null,"speed":"10 Gbps","interface":"PCIe x4","chipset":null,"color":"Black / Silver"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'StarTech ST10GPEXNDPI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card'));

-- ===== wireless-network-card (Wireless Network Card) =====
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'Gigabyte GC-WBAX210', 'Wi-Fi 6E', 925000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Wireless Network Card'), '{"name":"Gigabyte GC-WBAX210","protocol":"Wi-Fi 6E","interface":"PCIe x1","color":"Black / Silver","brand":"Gigabyte","source_file":"wireless-network-card.jsonl","source_category":"Wireless Network Card"}'::jsonb, '{"manufacturer":"Gigabyte","standard":"Wi-Fi 6","speed":null,"interface":"PCIe x1","bluetooth":null,"color":"Black / Silver"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'Gigabyte GC-WBAX210' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card'));
INSERT INTO products (name, description, price, quantity, low_stock_threshold, category_id, specifications, attributes) SELECT 'TP-Link Archer TBE550E', 'Wi-Fi 7', 2000000.00, 20, 5, (SELECT id FROM categories WHERE name = 'Wireless Network Card'), '{"name":"TP-Link Archer TBE550E","protocol":"Wi-Fi 7","interface":"PCIe x1","color":"Black","brand":"TP-Link","source_file":"wireless-network-card.jsonl","source_category":"Wireless Network Card"}'::jsonb, '{"manufacturer":null,"standard":"Wi-Fi 7","speed":null,"interface":"PCIe x1","bluetooth":null,"color":"Black"}'::jsonb WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.name = 'TP-Link Archer TBE550E' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card'));

COMMIT;
