-- Generated from cached image URLs
BEGIN;

-- Images for NZXT HUE 2 RGB Lighting Kit
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://microless.com/cdn/products/47a7e028928b5e9f4c0859070e809d1e-hi.jpg', true FROM products p WHERE p.name = 'NZXT HUE 2 RGB Lighting Kit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://microless.com/cdn/products/47a7e028928b5e9f4c0859070e809d1e-hi.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://microless.com/cdn/products/c94bac3864d0b61c30f75c838d709647-hi.jpg', false FROM products p WHERE p.name = 'NZXT HUE 2 RGB Lighting Kit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://microless.com/cdn/products/c94bac3864d0b61c30f75c838d709647-hi.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://files.pccasegear.com/UserFiles/AC-HUEP2-M1-f.jpg', false FROM products p WHERE p.name = 'NZXT HUE 2 RGB Lighting Kit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://files.pccasegear.com/UserFiles/AC-HUEP2-M1-f.jpg');

-- Images for NZXT Hue+
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://cyccomputer.pe/18560-home_default/sistema-de-iluminacion-led-nzxt-para-case-hue-pnac-hueps-m1.jpg', true FROM products p WHERE p.name = 'NZXT Hue+' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://cyccomputer.pe/18560-home_default/sistema-de-iluminacion-led-nzxt-para-case-hue-pnac-hueps-m1.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://cyccomputer.pe/18561-medium_default/sistema-de-iluminacion-led-nzxt-para-case-hue-pnac-hueps-m1.jpg', false FROM products p WHERE p.name = 'NZXT Hue+' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Accessory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://cyccomputer.pe/18561-medium_default/sistema-de-iluminacion-led-nzxt-para-case-hue-pnac-hueps-m1.jpg');

-- Images for Lian Li Uni Fan SL-Infinity 3-Pack
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://files.pccasegear.com/UserFiles/SL-INF-120-1-BK-lian-li-sl120-infinity-argb-pwm-120mm-black-ftr2.jpg', true FROM products p WHERE p.name = 'Lian Li Uni Fan SL-Infinity 3-Pack' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://files.pccasegear.com/UserFiles/SL-INF-120-1-BK-lian-li-sl120-infinity-argb-pwm-120mm-black-ftr2.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://igeekjo.com/cdn/shop/files/3_55e93325-9f31-4e86-bad6-da521baf4324.jpg?crop=center&height=1200&v=1688472823&width=1200', false FROM products p WHERE p.name = 'Lian Li Uni Fan SL-Infinity 3-Pack' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://igeekjo.com/cdn/shop/files/3_55e93325-9f31-4e86-bad6-da521baf4324.jpg?crop=center&height=1200&v=1688472823&width=1200');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.alternate.nl/p/600x600/4/1/Lian_Li_Uni_fan_SL_Infinity_120_triple_pack_case_fan@@1834014_36.jpg', false FROM products p WHERE p.name = 'Lian Li Uni Fan SL-Infinity 3-Pack' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.alternate.nl/p/600x600/4/1/Lian_Li_Uni_fan_SL_Infinity_120_triple_pack_case_fan@@1834014_36.jpg');

-- Images for Noctua NF-A12x25 PWM chromax.black.swap
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://songphuong.vn/Content/uploads/2025/03/Fan-Case-Noctua-NF-A12x25-PWM-Chromax-Black-Swap-7.jpg', true FROM products p WHERE p.name = 'Noctua NF-A12x25 PWM chromax.black.swap' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://songphuong.vn/Content/uploads/2025/03/Fan-Case-Noctua-NF-A12x25-PWM-Chromax-Black-Swap-7.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://product.hstatic.net/1000333506/product/n_case_t___n_nhi___t_noctua_nf_a12x25_pwm_chromax_black_swap_120mm__1__0f7b842d99c9415f9606fe4661d13ae4.jpg', false FROM products p WHERE p.name = 'Noctua NF-A12x25 PWM chromax.black.swap' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://product.hstatic.net/1000333506/product/n_case_t___n_nhi___t_noctua_nf_a12x25_pwm_chromax_black_swap_120mm__1__0f7b842d99c9415f9606fe4661d13ae4.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://sweetloot.my/wp-content/uploads/2022/04/1700db117e10ee77e85924c2de0aa082-1200x800.jpeg', false FROM products p WHERE p.name = 'Noctua NF-A12x25 PWM chromax.black.swap' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case Fan') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://sweetloot.my/wp-content/uploads/2022/04/1700db117e10ee77e85924c2de0aa082-1200x800.jpeg');

-- Images for Montech XR
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/my-11134207-7r98t-lwwd8xanz816b4', true FROM products p WHERE p.name = 'Montech XR' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/my-11134207-7r98t-lwwd8xanz816b4');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://img.pccasegear.com/tr:n-gallery/images/XR-B-add1.jpg', false FROM products p WHERE p.name = 'Montech XR' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://img.pccasegear.com/tr:n-gallery/images/XR-B-add1.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://images-cdn.ubuy.qa/66816d056ee94863572a1862-montech-xr-atx-mid-tower-pc-gaming.jpg', false FROM products p WHERE p.name = 'Montech XR' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://images-cdn.ubuy.qa/66816d056ee94863572a1862-montech-xr-atx-mid-tower-pc-gaming.jpg');

-- Images for Phanteks XT PRO
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://img.lazcdn.com/g/p/5c1d0dc1df449c457e36320078e10b59.jpg_720x720q80.jpg', true FROM products p WHERE p.name = 'Phanteks XT PRO' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://img.lazcdn.com/g/p/5c1d0dc1df449c457e36320078e10b59.jpg_720x720q80.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://files.pccasegear.com/UserFiles/PH-XT523P1-DBK01-phanteks-xt-pro-ultra-d-rgb-tempered-glass-case-black-product3.jpg', false FROM products p WHERE p.name = 'Phanteks XT PRO' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://files.pccasegear.com/UserFiles/PH-XT523P1-DBK01-phanteks-xt-pro-ultra-d-rgb-tempered-glass-case-black-product3.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://files.pccasegear.com/images/PH-XT523P1_BK01-thumb.jpg', false FROM products p WHERE p.name = 'Phanteks XT PRO' AND p.category_id = (SELECT id FROM categories WHERE name = 'Case') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://files.pccasegear.com/images/PH-XT523P1_BK01-thumb.jpg');

-- Images for Thermalright Peerless Assassin 120 SE
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71sEMx7F+TL._SL1500_.jpg', true FROM products p WHERE p.name = 'Thermalright Peerless Assassin 120 SE' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71sEMx7F+TL._SL1500_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/id-11134207-7r991-lschh9hmhiahe4', false FROM products p WHERE p.name = 'Thermalright Peerless Assassin 120 SE' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/id-11134207-7r991-lschh9hmhiahe4');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://kccshop.vn/media/product/3178-thermalright-peerless-assassin-120-se-----cpu-air-cooler-h1.jpeg', false FROM products p WHERE p.name = 'Thermalright Peerless Assassin 120 SE' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://kccshop.vn/media/product/3178-thermalright-peerless-assassin-120-se-----cpu-air-cooler-h1.jpeg');

-- Images for ARCTIC Liquid Freezer III Pro 360
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.arctic.de/media/c6/8f/e4/1741780195/Liquid_Freezer_III_Pro_360_Black_g00.png', true FROM products p WHERE p.name = 'ARCTIC Liquid Freezer III Pro 360' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.arctic.de/media/c6/8f/e4/1741780195/Liquid_Freezer_III_Pro_360_Black_g00.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.arctic.de/media/2c/5d/f0/1741775358/Liquid_Freezer_III_360_Black_ARGB_Rainbow_g00.png', false FROM products p WHERE p.name = 'ARCTIC Liquid Freezer III Pro 360' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.arctic.de/media/2c/5d/f0/1741775358/Liquid_Freezer_III_360_Black_ARGB_Rainbow_g00.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.arctic.de/media/9e/ed/6b/1742460214/Liquid_Freezer_III_360_Black_ARGB_Rainbow_g05.jpg', false FROM products p WHERE p.name = 'ARCTIC Liquid Freezer III Pro 360' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU Cooler') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.arctic.de/media/9e/ed/6b/1742460214/Liquid_Freezer_III_360_Black_ARGB_Rainbow_g05.jpg');

-- Images for AMD Ryzen 7 9800X3D
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.hwcooling.net/wp-content/uploads/2024/11/amd-ryzen-7-9800x3d-02.jpg', true FROM products p WHERE p.name = 'AMD Ryzen 7 9800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.hwcooling.net/wp-content/uploads/2024/11/amd-ryzen-7-9800x3d-02.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71aHvYUgX1L._AC_SL1500_.jpg', false FROM products p WHERE p.name = 'AMD Ryzen 7 9800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71aHvYUgX1L._AC_SL1500_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/06/18/10/LD0006181036.jpg', false FROM products p WHERE p.name = 'AMD Ryzen 7 9800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/06/18/10/LD0006181036.jpg');

-- Images for AMD Ryzen 7 7800X3D
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/61QON-Ik7OL._AC_SL1500_.jpg', true FROM products p WHERE p.name = 'AMD Ryzen 7 7800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/61QON-Ik7OL._AC_SL1500_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.pcstudio.in/wp-content/uploads/2023/01/Amd-Ryzen-7-7800X3D-Gaming-Processor-1.jpg', false FROM products p WHERE p.name = 'AMD Ryzen 7 7800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.pcstudio.in/wp-content/uploads/2023/01/Amd-Ryzen-7-7800X3D-Gaming-Processor-1.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://tpucdn.com/cpu-specs/images/chips/3022-package.jpg', false FROM products p WHERE p.name = 'AMD Ryzen 7 7800X3D' AND p.category_id = (SELECT id FROM categories WHERE name = 'CPU') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://tpucdn.com/cpu-specs/images/chips/3022-package.jpg');

-- Images for Apricorn Aegis Fortress L3
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/31C+ycWbA-L._AC_.jpg', true FROM products p WHERE p.name = 'Apricorn Aegis Fortress L3' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/31C+ycWbA-L._AC_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.networkhardwares.com/cdn/shop/products/1055341836_cb1f19a8-b126-4d98-9d9f-318065424864_1900x.jpg?v=1708783237', false FROM products p WHERE p.name = 'Apricorn Aegis Fortress L3' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.networkhardwares.com/cdn/shop/products/1055341836_cb1f19a8-b126-4d98-9d9f-318065424864_1900x.jpg?v=1708783237');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://dh9cuahs6ezpz.cloudfront.net/images/products/550x550/e3_71875.jpg', false FROM products p WHERE p.name = 'Apricorn Aegis Fortress L3' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://dh9cuahs6ezpz.cloudfront.net/images/products/550x550/e3_71875.jpg');

-- Images for Western Digital My Book Duo
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.westerndigital.com/content/dam/store/en-us/assets/products/desktop/my-book-duo-usb-3-1-hdd/gallery/my-book-duo-far-right.png.thumb.1280.1280.png', true FROM products p WHERE p.name = 'Western Digital My Book Duo' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.westerndigital.com/content/dam/store/en-us/assets/products/desktop/my-book-duo-usb-3-1-hdd/gallery/my-book-duo-far-right.png.thumb.1280.1280.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.imediastores.com/wp-content/uploads/2023/02/Western-Digital-My-Book-Duo-Desktop-RAID-External-Hard-Drive-24TB-2.jpg', false FROM products p WHERE p.name = 'Western Digital My Book Duo' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.imediastores.com/wp-content/uploads/2023/02/Western-Digital-My-Book-Duo-Desktop-RAID-External-Hard-Drive-24TB-2.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.imediastores.com/wp-content/uploads/2023/02/Western-Digital-My-Book-Duo-Desktop-RAID-External-Hard-Drive-24TB-1.jpg', false FROM products p WHERE p.name = 'Western Digital My Book Duo' AND p.category_id = (SELECT id FROM categories WHERE name = 'External Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.imediastores.com/wp-content/uploads/2023/02/Western-Digital-My-Book-Duo-Desktop-RAID-External-Hard-Drive-24TB-1.jpg');

-- Images for ARCTIC Case Fan Hub
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://static0.makeuseofimages.com/wordpress/wp-content/uploads/2021/08/ARCTIC-Case-Fan-Hub-ports.jpg', true FROM products p WHERE p.name = 'ARCTIC Case Fan Hub' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://static0.makeuseofimages.com/wordpress/wp-content/uploads/2021/08/ARCTIC-Case-Fan-Hub-ports.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pcroom.ge/image/cache/catalog/1-3807-47-500x500.png', false FROM products p WHERE p.name = 'ARCTIC Case Fan Hub' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pcroom.ge/image/cache/catalog/1-3807-47-500x500.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.arctic.de/media/c5/18/1f/1652943025/Case_Fan_Hub_G00.png', false FROM products p WHERE p.name = 'ARCTIC Case Fan Hub' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.arctic.de/media/c5/18/1f/1652943025/Case_Fan_Hub_G00.png');

-- Images for Lian Li UNI HUB – SL Controller
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://ae01.alicdn.com/kf/S3abc0be3985d4ba59c0d6ad73aad44fc3/LIAN-LI-SL120-SL140-AL120-Strimer-Plus-V1-V2-Controller-UNI-HUB-SL-Controller-For-120MM.jpg_.webp', true FROM products p WHERE p.name = 'Lian Li UNI HUB – SL Controller' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://ae01.alicdn.com/kf/S3abc0be3985d4ba59c0d6ad73aad44fc3/LIAN-LI-SL120-SL140-AL120-Strimer-Plus-V1-V2-Controller-UNI-HUB-SL-Controller-For-120MM.jpg_.webp');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/51rQfQ5ZqeL.jpg', false FROM products p WHERE p.name = 'Lian Li UNI HUB – SL Controller' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/51rQfQ5ZqeL.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://lian-li.com/wp-content/uploads/2021/10/003_sl.jpg', false FROM products p WHERE p.name = 'Lian Li UNI HUB – SL Controller' AND p.category_id = (SELECT id FROM categories WHERE name = 'Fan Controller') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://lian-li.com/wp-content/uploads/2021/10/003_sl.jpg');

-- Images for HP HyperX Cloud II
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'http://hyperx.com/cdn/shop/files/hyperx_cloud_ii_core_wireless_main_1.jpg?v=1688143845', true FROM products p WHERE p.name = 'HP HyperX Cloud II' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'http://hyperx.com/cdn/shop/files/hyperx_cloud_ii_core_wireless_main_1.jpg?v=1688143845');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://i5.walmartimages.com/asr/f9ade9e5-604d-4951-ad03-f6936b026a2f.2eb55b47082565f59cecd4d437e9114f.jpeg', false FROM products p WHERE p.name = 'HP HyperX Cloud II' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://i5.walmartimages.com/asr/f9ade9e5-604d-4951-ad03-f6936b026a2f.2eb55b47082565f59cecd4d437e9114f.jpeg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4505/4505300_sd.jpg', false FROM products p WHERE p.name = 'HP HyperX Cloud II' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4505/4505300_sd.jpg');

-- Images for HiFiMAN Susvara
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-id.img.susercontent.com/file/id-11134207-7r98v-lwe0pciwmyjfa6', true FROM products p WHERE p.name = 'HiFiMAN Susvara' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-id.img.susercontent.com/file/id-11134207-7r98v-lwe0pciwmyjfa6');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://headphones.com/cdn/shop/products/49722503-2015-423b-a06e-00ab15afb01d_66abb851-1ce5-40f1-9af7-e5ff5df5680f.png?v=1707787388&width=1946', false FROM products p WHERE p.name = 'HiFiMAN Susvara' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://headphones.com/cdn/shop/products/49722503-2015-423b-a06e-00ab15afb01d_66abb851-1ce5-40f1-9af7-e5ff5df5680f.png?v=1707787388&width=1946');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://audio46.com/cdn/shop/files/SusvaraUnveiled2_1200x1200.png?v=1717607918', false FROM products p WHERE p.name = 'HiFiMAN Susvara' AND p.category_id = (SELECT id FROM categories WHERE name = 'Headphones') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://audio46.com/cdn/shop/files/SusvaraUnveiled2_1200x1200.png?v=1717607918');

-- Images for Samsung 990 Pro
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/81WuG6lQuDL._AC_.jpg', true FROM products p WHERE p.name = 'Samsung 990 Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/81WuG6lQuDL._AC_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6559/6559270cv12d.jpg', false FROM products p WHERE p.name = 'Samsung 990 Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6559/6559270cv12d.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://images.samsung.com/is/image/samsung/p6pim/ca_fr/mz-v9p2t0b-am/gallery/ca-fr-990pro-nvme-m2-ssd-mz-v9p2t0b-am-534208574?$650_519_PNG$', false FROM products p WHERE p.name = 'Samsung 990 Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://images.samsung.com/is/image/samsung/p6pim/ca_fr/mz-v9p2t0b-am/gallery/ca-fr-990pro-nvme-m2-ssd-mz-v9p2t0b-am-534208574?$650_519_PNG$');

-- Images for Crucial P3 Plus
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509715cv12d.jpg', true FROM products p WHERE p.name = 'Crucial P3 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509715cv12d.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509710_sd.jpg', false FROM products p WHERE p.name = 'Crucial P3 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509710_sd.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509715cv1d.jpg', false FROM products p WHERE p.name = 'Crucial P3 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Internal Hard Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509715cv1d.jpg');

-- Images for HP HyperX Alloy Core
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/my-11134207-7rasl-m7lzloutjf8386', true FROM products p WHERE p.name = 'HP HyperX Alloy Core' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/my-11134207-7rasl-m7lzloutjf8386');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://th-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/4/P/4P4F5AA-1_T1679036360.png', false FROM products p WHERE p.name = 'HP HyperX Alloy Core' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://th-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/4/P/4P4F5AA-1_T1679036360.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://au-files.apjonlinecdn.com/landingpages/content-pages/rich-content-only/hyperx-keyboard/images/content-row-img-1-mobile-rgb.jpg', false FROM products p WHERE p.name = 'HP HyperX Alloy Core' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://au-files.apjonlinecdn.com/landingpages/content-pages/rich-content-only/hyperx-keyboard/images/content-row-img-1-mobile-rgb.jpg');

-- Images for Redragon K552
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71FSIp+tDNL._AC_UF894,1000_QL80_.jpg', true FROM products p WHERE p.name = 'Redragon K552' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71FSIp+tDNL._AC_UF894,1000_QL80_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6458/6458719_rd.jpg', false FROM products p WHERE p.name = 'Redragon K552' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6458/6458719_rd.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6458/6458719cv12d.jpg', false FROM products p WHERE p.name = 'Redragon K552' AND p.category_id = (SELECT id FROM categories WHERE name = 'Keyboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6458/6458719cv12d.jpg');

-- Images for Corsair Vengeance RGB 32 GB
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6448/6448612_sd.jpg', true FROM products p WHERE p.name = 'Corsair Vengeance RGB 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6448/6448612_sd.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6457/6457797_sd.jpg', false FROM products p WHERE p.name = 'Corsair Vengeance RGB 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6457/6457797_sd.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://asset.conrad.com/media10/isa/160267/c1/-/en/1715511_RB_01_FB/image.jpg', false FROM products p WHERE p.name = 'Corsair Vengeance RGB 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://asset.conrad.com/media10/isa/160267/c1/-/en/1715511_RB_01_FB/image.jpg');

-- Images for G.Skill Flare X5 32 GB
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://computechstore.in/wp-content/uploads/2023/01/G.Skill-Flare-X5-32GB-3.jpg', true FROM products p WHERE p.name = 'G.Skill Flare X5 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://computechstore.in/wp-content/uploads/2023/01/G.Skill-Flare-X5-32GB-3.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/05/98/08/LD0005980837_0005980917.jpg', false FROM products p WHERE p.name = 'G.Skill Flare X5 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/05/98/08/LD0005980837_0005980917.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.pcstudio.in/wp-content/uploads/2022/10/G.Skill-Flare-X5-32GB-16GBx2-DDR5-6000MHz-Desktop-Ram-Matte-Black-3.webp', false FROM products p WHERE p.name = 'G.Skill Flare X5 32 GB' AND p.category_id = (SELECT id FROM categories WHERE name = 'Memory') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.pcstudio.in/wp-content/uploads/2022/10/G.Skill-Flare-X5-32GB-16GBx2-DDR5-6000MHz-Desktop-Ram-Matte-Black-3.webp');

-- Images for KOORUI 24E3
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-id.img.susercontent.com/file/id-11134201-7r98p-lqg1sp5qb2tife', true FROM products p WHERE p.name = 'KOORUI 24E3' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-id.img.susercontent.com/file/id-11134201-7r98p-lqg1sp5qb2tife');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-id.img.susercontent.com/file/id-11134201-7rasa-m1cacsnjzxd1ae', false FROM products p WHERE p.name = 'KOORUI 24E3' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-id.img.susercontent.com/file/id-11134201-7rasa-m1cacsnjzxd1ae');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-id.img.susercontent.com/file/id-11134207-7qul6-lj3wvh4a63jv86', false FROM products p WHERE p.name = 'KOORUI 24E3' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-id.img.susercontent.com/file/id-11134207-7qul6-lj3wvh4a63jv86');

-- Images for Asus TUF Gaming VG27AQ
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.asus.com/media/global/products/x2ahzOXdioDZggLv/P_setting_xxx_0_90_end_500.png', true FROM products p WHERE p.name = 'Asus TUF Gaming VG27AQ' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.asus.com/media/global/products/x2ahzOXdioDZggLv/P_setting_xxx_0_90_end_500.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-th.img.susercontent.com/file/th-11134207-7r98o-lq381s631skkcb', false FROM products p WHERE p.name = 'Asus TUF Gaming VG27AQ' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-th.img.susercontent.com/file/th-11134207-7r98o-lq381s631skkcb');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://store.pcimage.com.my/image/shoppcimage/image/cache/data/all_product_images/product-7037/FYEyhY191638944105-850x850.jpg', false FROM products p WHERE p.name = 'Asus TUF Gaming VG27AQ' AND p.category_id = (SELECT id FROM categories WHERE name = 'Monitor') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://store.pcimage.com.my/image/shoppcimage/image/cache/data/all_product_images/product-7037/FYEyhY191638944105-850x850.jpg');

-- Images for Asus PRIME B650-PLUS WIFI
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://mediawebimg.asus.com/files/media/d1b30d89-702a-48a2-9947-d2191d7dac0f/img/new_product_imgs/03_Performance/Storage/pic_M.2.png', true FROM products p WHERE p.name = 'Asus PRIME B650-PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://mediawebimg.asus.com/files/media/d1b30d89-702a-48a2-9947-d2191d7dac0f/img/new_product_imgs/03_Performance/Storage/pic_M.2.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://mediawebimg.asus.com/files/media/d1b30d89-702a-48a2-9947-d2191d7dac0f/img/new_product_imgs/04_Customization/Personalization/Aura_Sync.png', false FROM products p WHERE p.name = 'Asus PRIME B650-PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://mediawebimg.asus.com/files/media/d1b30d89-702a-48a2-9947-d2191d7dac0f/img/new_product_imgs/04_Customization/Personalization/Aura_Sync.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://mediawebimg.asus.com/files/media/d1b30d89-702a-48a2-9947-d2191d7dac0f/img/new_product_imgs/00_spec/spec_mobile.png', false FROM products p WHERE p.name = 'Asus PRIME B650-PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://mediawebimg.asus.com/files/media/d1b30d89-702a-48a2-9947-d2191d7dac0f/img/new_product_imgs/00_spec/spec_mobile.png');

-- Images for MSI B650 GAMING PLUS WIFI
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://storage-asset.msi.com/global/picture/image/feature/mb/B650/B650-GAMING-PLUS-WIFI/b650-gaming-plus-wifi-hero-block02.png', true FROM products p WHERE p.name = 'MSI B650 GAMING PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://storage-asset.msi.com/global/picture/image/feature/mb/B650/B650-GAMING-PLUS-WIFI/b650-gaming-plus-wifi-hero-block02.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://storage-asset.msi.com/global/picture/image/feature/mb/B650/B650-GAMING-PLUS-WIFI/b650-gaming-plus-wifi-hero-block01.png', false FROM products p WHERE p.name = 'MSI B650 GAMING PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://storage-asset.msi.com/global/picture/image/feature/mb/B650/B650-GAMING-PLUS-WIFI/b650-gaming-plus-wifi-hero-block01.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/06/03/76/LD0006037607.jpg', false FROM products p WHERE p.name = 'MSI B650 GAMING PLUS WIFI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Motherboard') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/06/03/76/LD0006037607.jpg');

-- Images for Logitech G305 LIGHTSPEED
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/06/00/22/LD0006002279.jpg', true FROM products p WHERE p.name = 'Logitech G305 LIGHTSPEED' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/06/00/22/LD0006002279.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://microless.com/cdn/products/536be5b390f55a5d6f4066277359fe36-hi.jpg', false FROM products p WHERE p.name = 'Logitech G305 LIGHTSPEED' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://microless.com/cdn/products/536be5b390f55a5d6f4066277359fe36-hi.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://microless.com/cdn/products/fcf14753c49382bc080282bbb6d81b0a-hi.jpg', false FROM products p WHERE p.name = 'Logitech G305 LIGHTSPEED' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://microless.com/cdn/products/fcf14753c49382bc080282bbb6d81b0a-hi.jpg');

-- Images for Logitech G502 Hero
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://scale.coolshop-cdn.com/product-media.coolshop-cdn.com/AJ24DP/4b0cea07217b479aa18b05c47c138c25.jpg/f/logitech-g502-hero-high-performance-gaming-mouse.jpg', true FROM products p WHERE p.name = 'Logitech G502 Hero' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://scale.coolshop-cdn.com/product-media.coolshop-cdn.com/AJ24DP/4b0cea07217b479aa18b05c47c138c25.jpg/f/logitech-g502-hero-high-performance-gaming-mouse.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://dist.contentdriver.com.au/logitech/G502-HERO-910-005472/images/prog-buttons-mobile.jpg', false FROM products p WHERE p.name = 'Logitech G502 Hero' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://dist.contentdriver.com.au/logitech/G502-HERO-910-005472/images/prog-buttons-mobile.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/350cf911-21f0-4aa7-83a7-53154d30164a.jpg', false FROM products p WHERE p.name = 'Logitech G502 Hero' AND p.category_id = (SELECT id FROM categories WHERE name = 'Mouse') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/350cf911-21f0-4aa7-83a7-53154d30164a.jpg');

-- Images for LG WH14NS40
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://cdn.shopclues.com/images/thumbnails/8730/320/320/lgdatastoragewh14ns40large02_1391514237.jpg', true FROM products p WHERE p.name = 'LG WH14NS40' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://cdn.shopclues.com/images/thumbnails/8730/320/320/lgdatastoragewh14ns40large02_1391514237.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.cclonline.com/images/avante/WH14NS40-230317-02.jpg?width=1600&height=1600', false FROM products p WHERE p.name = 'LG WH14NS40' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.cclonline.com/images/avante/WH14NS40-230317-02.jpg?width=1600&height=1600');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.itcreations.com/images/products/large/wh14ns40.jpg?3142013', false FROM products p WHERE p.name = 'LG WH14NS40' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.itcreations.com/images/products/large/wh14ns40.jpg?3142013');

-- Images for Lite-On iHAS124-14
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71Zn6sEUAeL._AC_SS450_.jpg', true FROM products p WHERE p.name = 'Lite-On iHAS124-14' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71Zn6sEUAeL._AC_SS450_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/61flPHJF3QL._AC_SL1500_.jpg', false FROM products p WHERE p.name = 'Lite-On iHAS124-14' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/61flPHJF3QL._AC_SL1500_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'http://www.ascendtech.us/mmImages/b_0/iHAS12414UC-01.jpg', false FROM products p WHERE p.name = 'Lite-On iHAS124-14' AND p.category_id = (SELECT id FROM categories WHERE name = 'Optical Drive') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'http://www.ascendtech.us/mmImages/b_0/iHAS12414UC-01.jpg');

-- Images for Microsoft Windows 11 Home OEM - DVD 64-bit
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media-cdn.bnn.in.th/453821/microsoft-windows-home-11-64bit-eng-intl-1pk-dsp-oei-dvd-oem-kw9-00632ms-2-square_medium.jpg', true FROM products p WHERE p.name = 'Microsoft Windows 11 Home OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media-cdn.bnn.in.th/453821/microsoft-windows-home-11-64bit-eng-intl-1pk-dsp-oei-dvd-oem-kw9-00632ms-2-square_medium.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://sc04.alicdn.com/kf/A629c1e0ac12244a2819e662845f73e301.jpg', false FROM products p WHERE p.name = 'Microsoft Windows 11 Home OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://sc04.alicdn.com/kf/A629c1e0ac12244a2819e662845f73e301.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://cintegral.cl/wp-content/uploads/2023/03/2600-a16-WINDOWS-11-HOME-64-BITS-OEM-SPA-DVD.jpg', false FROM products p WHERE p.name = 'Microsoft Windows 11 Home OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://cintegral.cl/wp-content/uploads/2023/03/2600-a16-WINDOWS-11-HOME-64-BITS-OEM-SPA-DVD.jpg');

-- Images for Microsoft Windows 11 Pro OEM - DVD 64-bit
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://images-cdn.ubuy.co.in/64e8b0e009d8490ea252b06b-microsoft-windows-11-professional-oem-64.jpg', true FROM products p WHERE p.name = 'Microsoft Windows 11 Pro OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://images-cdn.ubuy.co.in/64e8b0e009d8490ea252b06b-microsoft-windows-11-professional-oem-64.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://c1.neweggimages.com/ProductImage/32-350-934-S01.jpg', false FROM products p WHERE p.name = 'Microsoft Windows 11 Pro OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://c1.neweggimages.com/ProductImage/32-350-934-S01.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media-cdn.bnn.in.th/193286/microsoft-windows11-pro-64bit-fqc-10528-1-square_medium.jpg', false FROM products p WHERE p.name = 'Microsoft Windows 11 Pro OEM - DVD 64-bit' AND p.category_id = (SELECT id FROM categories WHERE name = 'Operating System') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media-cdn.bnn.in.th/193286/microsoft-windows11-pro-64bit-fqc-10528-1-square_medium.jpg');

-- Images for MSI MAG A750GL PCIE5
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71Bp8cXNjeL._AC_.jpg', true FROM products p WHERE p.name = 'MSI MAG A750GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71Bp8cXNjeL._AC_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6562/6562433_sd.jpg', false FROM products p WHERE p.name = 'MSI MAG A750GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6562/6562433_sd.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/06/05/15/LD0006051585.jpg', false FROM products p WHERE p.name = 'MSI MAG A750GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/06/05/15/LD0006051585.jpg');

-- Images for MSI MAG A850GL PCIE5
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://asset.msi.com/resize/image/global/product/product_1688640881ab817ac1105b164c449c87c3fedb512d.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png', true FROM products p WHERE p.name = 'MSI MAG A850GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://asset.msi.com/resize/image/global/product/product_1688640881ab817ac1105b164c449c87c3fedb512d.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://asset.msi.com/resize/image/global/product/product_16861307271614336078f5c76c62ff157c01353710.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png', false FROM products p WHERE p.name = 'MSI MAG A850GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://asset.msi.com/resize/image/global/product/product_16861307271614336078f5c76c62ff157c01353710.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://static3.webx.pk/files/19643/Images/msi-mag-a850gl-pcie5-gold-psu-price-in-pakistan-2-19643-2119197-250624092131455.jpg', false FROM products p WHERE p.name = 'MSI MAG A850GL PCIE5' AND p.category_id = (SELECT id FROM categories WHERE name = 'Power Supply') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://static3.webx.pk/files/19643/Images/msi-mag-a850gl-pcie5-gold-psu-price-in-pakistan-2-19643-2119197-250624092131455.jpg');

-- Images for Creative Labs Sound BlasterX AE-5 Plus
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-ph.img.susercontent.com/file/sg-11134201-7rd5c-m78p124i6okw44', true FROM products p WHERE p.name = 'Creative Labs Sound BlasterX AE-5 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-ph.img.susercontent.com/file/sg-11134201-7rd5c-m78p124i6okw44');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://elchapuzasinformatico.com/wp-content/uploads/2020/05/Creative-Sound-BlasterX-AE-5-Plus-10.jpg', false FROM products p WHERE p.name = 'Creative Labs Sound BlasterX AE-5 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://elchapuzasinformatico.com/wp-content/uploads/2020/05/Creative-Sound-BlasterX-AE-5-Plus-10.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://sm.pcmag.com/pcmag_gr/photo/default/dsc-0201_42em.jpg', false FROM products p WHERE p.name = 'Creative Labs Sound BlasterX AE-5 Plus' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://sm.pcmag.com/pcmag_gr/photo/default/dsc-0201_42em.jpg');

-- Images for Creative Labs Sound Blaster AE-9
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://d287ku8w5owj51.cloudfront.net/inline/products/23304/ae9_feature_5a.jpg', true FROM products p WHERE p.name = 'Creative Labs Sound Blaster AE-9' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://d287ku8w5owj51.cloudfront.net/inline/products/23304/ae9_feature_5a.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://c1.neweggimages.com/productimage/nb1280/29-102-105-V08.jpg', false FROM products p WHERE p.name = 'Creative Labs Sound Blaster AE-9' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://c1.neweggimages.com/productimage/nb1280/29-102-105-V08.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://c1.neweggimages.com/productimage/nb1280/29-102-105-V10.jpg', false FROM products p WHERE p.name = 'Creative Labs Sound Blaster AE-9' AND p.category_id = (SELECT id FROM categories WHERE name = 'Sound Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://c1.neweggimages.com/productimage/nb1280/29-102-105-V10.jpg');

-- Images for Creative Labs Pebble 2.0
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://d287ku8w5owj51.cloudfront.net/images/products/large/pdt_23168.1.png?format=jpg&quality=80&height=1000', true FROM products p WHERE p.name = 'Creative Labs Pebble 2.0' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://d287ku8w5owj51.cloudfront.net/images/products/large/pdt_23168.1.png?format=jpg&quality=80&height=1000');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://d287ku8w5owj51.cloudfront.net/images/products/hero/creative-pebble/hero-pebble.jpg', false FROM products p WHERE p.name = 'Creative Labs Pebble 2.0' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://d287ku8w5owj51.cloudfront.net/images/products/hero/creative-pebble/hero-pebble.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://shopcgx.com/cdn/shop/products/2_yq99-y5.jpg?v=1653282994', false FROM products p WHERE p.name = 'Creative Labs Pebble 2.0' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://shopcgx.com/cdn/shop/products/2_yq99-y5.jpg?v=1653282994');

-- Images for SteelSeries Arena 9 EU
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.steelseriescdn.com/thumbs/catalog/items/61552/7c08864a1a5347208f6727781d8e8140.png.500x400_q100_crop-fit_optimize.png', true FROM products p WHERE p.name = 'SteelSeries Arena 9 EU' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.steelseriescdn.com/thumbs/catalog/items/61552/7c08864a1a5347208f6727781d8e8140.png.500x400_q100_crop-fit_optimize.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.maxgaming.dk/bilder/artiklar/zoom/22185_2.jpg?m=1661178292', false FROM products p WHERE p.name = 'SteelSeries Arena 9 EU' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.maxgaming.dk/bilder/artiklar/zoom/22185_2.jpg?m=1661178292');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/985a6d47-18bc-4752-a615-dcb1112e338d.jpg', false FROM products p WHERE p.name = 'SteelSeries Arena 9 EU' AND p.category_id = (SELECT id FROM categories WHERE name = 'Speakers') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/985a6d47-18bc-4752-a615-dcb1112e338d.jpg');

-- Images for Arctic Silver 5 High-Density Polysynthetic Silver
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-ph.img.susercontent.com/file/my-11134207-7r98r-lmr1rbzzfn4jbc', true FROM products p WHERE p.name = 'Arctic Silver 5 High-Density Polysynthetic Silver' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-ph.img.susercontent.com/file/my-11134207-7r98r-lmr1rbzzfn4jbc');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.quietpc.com/images/products/arcticsilver5-large.jpg', false FROM products p WHERE p.name = 'Arctic Silver 5 High-Density Polysynthetic Silver' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.quietpc.com/images/products/arcticsilver5-large.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://static.wixstatic.com/media/d8131d_a66607c909734869b05c9bf9534cf83b~mv2.jpg/v1/fill/w_530,h_530,al_c,q_80,enc_auto/d8131d_a66607c909734869b05c9bf9534cf83b~mv2.jpg', false FROM products p WHERE p.name = 'Arctic Silver 5 High-Density Polysynthetic Silver' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://static.wixstatic.com/media/d8131d_a66607c909734869b05c9bf9534cf83b~mv2.jpg/v1/fill/w_530,h_530,al_c,q_80,enc_auto/d8131d_a66607c909734869b05c9bf9534cf83b~mv2.jpg');

-- Images for Thermal Grizzly Kryonaut
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-sg.img.susercontent.com/file/sg-11134201-7rdw2-lzftb67ibcs407', true FROM products p WHERE p.name = 'Thermal Grizzly Kryonaut' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-sg.img.susercontent.com/file/sg-11134201-7rdw2-lzftb67ibcs407');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71v-Qea5lGL.jpg', false FROM products p WHERE p.name = 'Thermal Grizzly Kryonaut' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71v-Qea5lGL.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-th.img.susercontent.com/file/af371c833f1417bbd2532f5fe318712a', false FROM products p WHERE p.name = 'Thermal Grizzly Kryonaut' AND p.category_id = (SELECT id FROM categories WHERE name = 'Thermal Paste') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-th.img.susercontent.com/file/af371c833f1417bbd2532f5fe318712a');

-- Images for CyberPower CP1500PFCLCD
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/71jf6zxksUL.jpg', true FROM products p WHERE p.name = 'CyberPower CP1500PFCLCD' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/71jf6zxksUL.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://dl4jz3rbrsfum.cloudfront.net/images/feature-focus/7641-CP1500PFCLCD_Feature_Focus_vo2_r01.jpg', false FROM products p WHERE p.name = 'CyberPower CP1500PFCLCD' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://dl4jz3rbrsfum.cloudfront.net/images/feature-focus/7641-CP1500PFCLCD_Feature_Focus_vo2_r01.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.cyberpowersystems.com/wp-content/uploads/2017/04/CP1500PFCLCD_L2.jpg', false FROM products p WHERE p.name = 'CyberPower CP1500PFCLCD' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.cyberpowersystems.com/wp-content/uploads/2017/04/CP1500PFCLCD_L2.jpg');

-- Images for APC SURT20KRMXLT
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://service.pcconnection.com/images/inhouse/7BB2B41B-9BCE-466E-9A2B-970C82A9D134.jpg', true FROM products p WHERE p.name = 'APC SURT20KRMXLT' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://service.pcconnection.com/images/inhouse/7BB2B41B-9BCE-466E-9A2B-970C82A9D134.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://www.nobreak.store/wp-content/uploads/2018/02/SURT20KRMXLT-Frente.jpg', false FROM products p WHERE p.name = 'APC SURT20KRMXLT' AND p.category_id = (SELECT id FROM categories WHERE name = 'UPS') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://www.nobreak.store/wp-content/uploads/2018/02/SURT20KRMXLT-Frente.jpg');

-- Images for MSI GeForce RTX 3060 Ventus 2X 12G
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://asset.msi.com/resize/image/global/product/product_1610444642f817750da1dd6872a146f4af45ab4705.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png', true FROM products p WHERE p.name = 'MSI GeForce RTX 3060 Ventus 2X 12G' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://asset.msi.com/resize/image/global/product/product_1610444642f817750da1dd6872a146f4af45ab4705.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://file.hstatic.net/1000026716/file/gearvn-msi-geforce-rtx-3060-ventus-2x-12g-oc-02_7c7e1c7213c543a6ae0ae38ee6573c6c.png', false FROM products p WHERE p.name = 'MSI GeForce RTX 3060 Ventus 2X 12G' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://file.hstatic.net/1000026716/file/gearvn-msi-geforce-rtx-3060-ventus-2x-12g-oc-02_7c7e1c7213c543a6ae0ae38ee6573c6c.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://static3.webx.pk/files/19643/Images/71tdusp8ool.-ac-sl1500--19643-0-160522070109582.jpg', false FROM products p WHERE p.name = 'MSI GeForce RTX 3060 Ventus 2X 12G' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://static3.webx.pk/files/19643/Images/71tdusp8ool.-ac-sl1500--19643-0-160522070109582.jpg');

-- Images for Sapphire PULSE
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/81n9vllhNeL.jpg', true FROM products p WHERE p.name = 'Sapphire PULSE' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/81n9vllhNeL.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/813l7nGCBxL._AC_SL1500_.jpg', false FROM products p WHERE p.name = 'Sapphire PULSE' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/813l7nGCBxL._AC_SL1500_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/06/06/15/LD0006061513.jpg', false FROM products p WHERE p.name = 'Sapphire PULSE' AND p.category_id = (SELECT id FROM categories WHERE name = 'Video Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/06/06/15/LD0006061513.jpg');

-- Images for Razer Kiyo Pro Ultra
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://product.hstatic.net/200000637319/product/20_22000__1__5dcd6e3dde8f4f7e825a1fe5fda54c43_master.png', true FROM products p WHERE p.name = 'Razer Kiyo Pro Ultra' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://product.hstatic.net/200000637319/product/20_22000__1__5dcd6e3dde8f4f7e825a1fe5fda54c43_master.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://product.hstatic.net/200000637319/product/20_22000__2__959788227a9f405caa38562ed10b3a36_master.png', false FROM products p WHERE p.name = 'Razer Kiyo Pro Ultra' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://product.hstatic.net/200000637319/product/20_22000__2__959788227a9f405caa38562ed10b3a36_master.png');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://assets2.razerzone.com/images/pnx.assets/4e201a3d1c57d7a7e403fcb587349276/razer-kiyo-pro-ultra-ogimage_1200x630.jpg', false FROM products p WHERE p.name = 'Razer Kiyo Pro Ultra' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://assets2.razerzone.com/images/pnx.assets/4e201a3d1c57d7a7e403fcb587349276/razer-kiyo-pro-ultra-ogimage_1200x630.jpg');

-- Images for Logitech BRIO Ultra HD Pro
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://cdn.shopify.com/s/files/1/0064/7168/0115/products/Logitech_Brio_Ultra_HD_Pro_Webcam_2_1400x.jpg?v=1561389788', true FROM products p WHERE p.name = 'Logitech BRIO Ultra HD Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://cdn.shopify.com/s/files/1/0064/7168/0115/products/Logitech_Brio_Ultra_HD_Pro_Webcam_2_1400x.jpg?v=1561389788');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://hdinteractive.com.au/wp-content/uploads/2020/02/Logitech_HD_PRO_webcam_A_1200_2.jpg', false FROM products p WHERE p.name = 'Logitech BRIO Ultra HD Pro' AND p.category_id = (SELECT id FROM categories WHERE name = 'Webcam') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://hdinteractive.com.au/wp-content/uploads/2020/02/Logitech_HD_PRO_webcam_A_1200_2.jpg');

-- Images for TP-Link TG-3468
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/vn-11134207-7ras8-m2w8utkaq3zub5', true FROM products p WHERE p.name = 'TP-Link TG-3468' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/vn-11134207-7ras8-m2w8utkaq3zub5');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/sg-11134202-7rdya-lzvkbnrv1fw778', false FROM products p WHERE p.name = 'TP-Link TG-3468' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/sg-11134202-7rdya-lzvkbnrv1fw778');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/b6fe854c0e00715fb3d2b9bfec125892', false FROM products p WHERE p.name = 'TP-Link TG-3468' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/b6fe854c0e00715fb3d2b9bfec125892');

-- Images for StarTech ST10GPEXNDPI
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.officedepot.com/images/f_auto,q_auto,e_sharpen,h_450/products/678108/678108_o66_et_4377216/678108', true FROM products p WHERE p.name = 'StarTech ST10GPEXNDPI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.officedepot.com/images/f_auto,q_auto,e_sharpen,h_450/products/678108/678108_o66_et_4377216/678108');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.officedepot.com/images/f_auto,q_auto,e_sharpen,h_450/products/678108/678108_o65_et_4233907/678108', false FROM products p WHERE p.name = 'StarTech ST10GPEXNDPI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.officedepot.com/images/f_auto,q_auto,e_sharpen,h_450/products/678108/678108_o65_et_4233907/678108');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://images.prom.ua/4869233024_w640_h640_4869233024.jpg', false FROM products p WHERE p.name = 'StarTech ST10GPEXNDPI' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wired Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://images.prom.ua/4869233024_w640_h640_4869233024.jpg');

-- Images for Gigabyte GC-WBAX210
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://i.ytimg.com/vi/OXV9F5UABlQ/maxresdefault.jpg', true FROM products p WHERE p.name = 'Gigabyte GC-WBAX210' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://i.ytimg.com/vi/OXV9F5UABlQ/maxresdefault.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://c1.neweggimages.com/productimage/nb1280/V009D2301260GHA0H86.jpg', false FROM products p WHERE p.name = 'Gigabyte GC-WBAX210' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://c1.neweggimages.com/productimage/nb1280/V009D2301260GHA0H86.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://media.ldlc.com/r1600/ld/products/00/05/82/04/LD0005820484_1.jpg', false FROM products p WHERE p.name = 'Gigabyte GC-WBAX210' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://media.ldlc.com/r1600/ld/products/00/05/82/04/LD0005820484_1.jpg');

-- Images for TP-Link Archer TBE550E
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/715TVvocyQL.jpg', true FROM products p WHERE p.name = 'TP-Link Archer TBE550E' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/715TVvocyQL.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://m.media-amazon.com/images/I/61FzXXe4WWL._SL1500_.jpg', false FROM products p WHERE p.name = 'TP-Link Archer TBE550E' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://m.media-amazon.com/images/I/61FzXXe4WWL._SL1500_.jpg');
INSERT INTO product_images (product_id, image_url, is_primary) SELECT p.id, 'https://down-my.img.susercontent.com/file/my-11134207-7ras9-m400py8dd48pee', false FROM products p WHERE p.name = 'TP-Link Archer TBE550E' AND p.category_id = (SELECT id FROM categories WHERE name = 'Wireless Network Card') AND NOT EXISTS (SELECT 1 FROM product_images i WHERE i.product_id = p.id AND i.image_url = 'https://down-my.img.susercontent.com/file/my-11134207-7ras9-m400py8dd48pee');

COMMIT;
